### ISSUE TITLE
Please Update Your Database - Error

### ISSUE THREAD

**Issue by drewrawitz** [rgranadino/mage2_vagrant#12]
Hi,

I am trying to get this set up, I am on Mac OSX 10.10.1, and this is the error I am getting when I visit **mage2.dev**

	Please update your database: Run "php â€“f index.php update" from the Magento root/setup directory.
	The following modules are outdated:
	Magento_Store schema: current version - 2.0.0.0, required version - 2.0.0
	Magento_Store data: current version - 2.0.0.0, required version - 2.0.0
	Magento_Cms schema: current version - 2.0.0.1, required version - 2.0.0
	Magento_Cms data: current version - 2.0.0.1, required version - 2.0.0
	Magento_AdminNotification schema: current version - 2.0.0.0, required version - 2.0.0
	Magento_AdminNotification data: current version - 2.0.0.0, required version - 2.0.0
	#0 [internal function]: Magento\Framework\Module\Plugin\DbStatusValidator->aroundDispatch(Object(Magento\Framework\App\FrontController\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
	#1 /vagrant/data/magento2/lib/internal/Magento/Framework/Interception/Chain/Chain.php(62): call_user_func_array(Array, Array)
	#2 /vagrant/data/magento2/lib/internal/Magento/Framework/Interception/Chain/Chain.php(57): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\\Framewo...', 'dispatch', Object(Magento\Framework\App\FrontController\Interceptor), Array, 'front-controlle...')
	#3 /vagrant/data/magento2/app/code/Magento/PageCache/Model/App/FrontController/VarnishPlugin.php(53): Magento\Framework\Interception\Chain\Chain->Magento\Framework\Interception\Chain\{closure}(Object(Magento\Framework\App\Request\Http))
	#4 [internal function]: Magento\PageCache\Model\App\FrontController\VarnishPlugin->aroundDispatch(Object(Magento\Framework\App\FrontController\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
	#5 /vagrant/data/magento2/lib/internal/Magento/Framework/Interception/Chain/Chain.php(62): call_user_func_array(Array, Array)
	#6 /vagrant/data/magento2/var/generation/Magento/Framework/App/FrontController/Interceptor.php(90): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\\Framewo...', 'dispatch', Object(Magento\Framework\App\FrontController\Interceptor), Array, 'front-controlle...')
	#7 /vagrant/data/magento2/app/code/Magento/PageCache/Model/App/FrontController/BuiltinPlugin.php(71): Magento\Framework\App\FrontController\Interceptor->Magento\Framework\App\FrontController\{closure}(Object(Magento\Framework\App\Request\Http))
	#8 [internal function]: Magento\PageCache\Model\App\FrontController\BuiltinPlugin->aroundDispatch(Object(Magento\Framework\App\FrontController\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
	#9 /vagrant/data/magento2/var/generation/Magento/Framework/App/FrontController/Interceptor.php(95): call_user_func_array(Array, Array)
	#10 /vagrant/data/magento2/var/generation/Magento/Framework/App/FrontController/Interceptor.php(119): Magento\Framework\App\FrontController\Interceptor->___callPlugins('dispatch', Array, Array)
	#11 /vagrant/data/magento2/lib/internal/Magento/Framework/App/Http.php(114): Magento\Framework\App\FrontController\Interceptor->dispatch(Object(Magento\Framework\App\Request\Http))
	#12 /vagrant/data/magento2/lib/internal/Magento/Framework/App/Bootstrap.php(244): Magento\Framework\App\Http->launch()
	#13 /vagrant/data/magento2/index.php(38): Magento\Framework\App\Bootstrap->run(Object(Magento\Framework\App\Http))
	#14 {main}

I went into /setup/ and ran `php -f index.php update` and it ran through the list with no errors, but this error message continues to stay up. 

Any ideas?

**Comment by jigneshthummar** [comment]
i have same issue in windows WAMP

**Comment by therouv** [comment]
Could you please try again with latest release? Magento heavily refactored CLI behaviour, especially by releasing a custom CLI application (bin/magento)
