### ISSUE TITLE
nfs mount error on mac osx

### ISSUE THREAD

**Issue by lfolco** [rgranadino/mage2_vagrant#22]
hi-

when running vagrant up, i'm seeing the following errors:

```
[default] Setting hostname...
[default] Configuring and enabling network interfaces...
[default] Mounting shared folders...
[default] -- /tmp/vagrant-puppet/manifests
[default] -- /tmp/vagrant-puppet/modules-0
[default] Exporting NFS shared folders...
Preparing to edit /etc/exports. Administrator privileges will be required...
[default] Mounting NFS shared folders...
The following SSH command responded with a non-zero exit status.
Vagrant assumes that this means the command failed!

mount -o 'vers=3,udp' 192.168.56.1:'/Users/lfolco/Sites/study/magento/magento2/vagrant' /vagrant

Stdout from the command:


Stderr from the command:

stdin: is not a tty
mount: wrong fs type, bad option, bad superblock on 192.168.56.1:/Users/lfolco/Sites/study/magento/magento2/vagrant,
       missing codepage or helper program, or other error
       (for several filesystems (e.g. nfs, cifs) you might
       need a /sbin/mount.<type> helper program)
       In some cases useful info is found in syslog - try
       dmesg | tail  or so
```

it seems as if it's attempting to mount the folder before nfs-common is installed?

**Comment by rgranadino** [comment]
Hi @lfolco , that could be it. @avra911 opened PR #19 but perhaps which I merged. Perhaps having it in puppet is too late as it would need the mount first before the provision via puppet happens. I'll try to replicate the issue and see what other workarounds there are.

**Comment by lfolco** [comment]
turns out that upgrading from my really, really old version of vagrant fixed it right up!

**Comment by avra911** [comment]
Indeed, i read that is a bug of vagrant. My fix was too fast to be proper. Like @rgranadino said, it should be provisioning before mount, which is a different approach

Best,
R
