### ISSUE TITLE
Error in Windows

### ISSUE THREAD

**Issue by cerebrumbr** [rgranadino/mage2_vagrant#33]
See image ...

![img](https://cloud.githubusercontent.com/assets/2263217/7687643/09dc3770-fd75-11e4-8d18-4f6a53e6e50a.png)

**Comment by therouv** [comment]
Hi @cerebrumbr 
Are the puppet submodules (in subfolder "puppet_modules") correctly installed? If not: can you delete the repository and clone recursively again?

```bash
git clone --recursive git@github.com:rgranadino/mage2_vagrant.git
```

Alternatively, you can also re-init the submodules (in an existing cloned repository) via the following command:

```bash
git submodule update --init --recursive
```
