### ISSUE TITLE
reinstall -s generates "Integrity contraint violation"

### ISSUE THREAD

**Issue by ddeppner** [rgranadino/mage2_vagrant#34]
Reported here:  https://github.com/magento/magento2/issues/1308

I just tried to use mage2_vagrant for the first time and it errored out.  I found the issue reported above, so I expect it's not caused by your project, but figured I'd report it, in case it's due to a server config issue.  Sorry I don't have time to work on researching this further right now so I'm not contributing much that's useful.

**Comment by therouv** [comment]
Hi @ddeppner !
Magento has now published new sample data (see https://github.com/magento/magento2/issues/1308 ). I've changed the reinstall script in 95b39bceb383ce26e45cf008e8cc37d766857708 and testet the installation in our vagrant box. Everything seems to work fine again.

**Comment by ddeppner** [comment]
It works perfectly for me now.
