### ISSUE TITLE
NFS sync

### ISSUE THREAD

**Issue by sonbui00** [rgranadino/mage2_vagrant#35]
"flock(2) does not lock files over NFS."
Magento use it.
So I think many people will have some problem with NFS sync.

**Comment by rgranadino** [comment]
Is this an error you're seeing while running something (indexers or some other process that shouldn't be ran in parallel)?

**Comment by sonbui00** [comment]
The error will not occur. But it is very slow for waiting. The anything use PHP flock function that will very slow(Magento use Zend, Zend cache use flock). You can see http://php.net/manual/en/function.flock.php. It don't work with NFS.
I can't complete to install Magento .When I change sync file to VBox default. I work well.
