### ISSUE TITLE
[PDOException] SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '0' for key 'PRIMARY'

### ISSUE THREAD

**Issue by comunidademagento** [rgranadino/mage2_vagrant#36]
Dear @rgranadino 

This error presented in installation process (log) and when try run this command bin/magento setup:upgrade

![captura de tela de 2015-09-21 16 29 40](https://cloud.githubusercontent.com/assets/7476455/10002567/51b7d146-607e-11e5-81d4-b6623ede9d75.png)

**Comment by therouv** [comment]
Hi @comunidademagento This should no longer be happening with the latest M2 release.
