### ISSUE TITLE
Installation fails on step #6 (DB setup)

### ISSUE THREAD

**Issue by brendanfalkowski** [rgranadino/mage2_vagrant#37]
Still trying to get M2 installed. I got past the composer / GitHub oAuth part but unchecked all boxes. It didn't seem right granted access to my private repos to install this. Seemed to still work.

Step 6 should be changed to http://mage2.dev/setup/ because accessing the root directory gives a permissions error.

I got through to the DB setup page, but it failed using the credentials supplied in the readme. Kind of a weird error response too. See attached.

All the server readiness checks did pass.

![screen shot 2015-09-23 at 4 18 03 pm](https://cloud.githubusercontent.com/assets/214924/10057605/220623c0-620f-11e5-9681-df924f898b8d.png)

**Comment by rgranadino** [comment]
Unfortunately I wasn't able to reproduce the issue you experienced. It is indeed odd as it seems to indicate some Apache/web server error. It might be related to the permission error you were seeing when accessing http://mage2.dev directly, after the composer install I was able to get to the web root which redirected me to the setup page. I was only able to get through the web installation once but failed after some additional testing. Seems like there might still be some kinks to be worked out.

I'd suggest to try and install it via the provided `reinstall` command that's available I was able to get it up and running after that.

As for the token, the only permission you need to grant it is the `public_repo` access, all the other boxes should be unchecked. You can read more about the need for generating a key [here](http://devdocs.magento.com/guides/v2.0/install-gde/trouble/git/tshoot_rate-limit.html).

**Comment by brendanfalkowski** [comment]
Thanks! The `reinstall` alternative in step 6 worked. First time I've gotten Magento 2 running in almost 18 months. Immediately after tried `reinstall -s` for sample data and that works too.

If the web-based installer is buggy, I'd probably make that the secondary option. I would've done this command first if I'd seen that, but otherwise was just curious how it went (and then assumed the whole thing was broken).
