### ISSUE TITLE
Backend still show Magento ver. 0.74.0-beta12

### ISSUE THREAD

**Issue by riconeitzel** [rgranadino/mage2_vagrant#38]
I just downloaded your package … fresh … from scratch … and after all these setup routines … it says … Magento ver. 0.74.0-beta12 … WHY??? :( Is it just me? Is it Magento? Did they forget to change this string? Thanks for your help …

Rico

**Comment by riconeitzel** [comment]
Okay … never mind … you're using mage2.dev as a built in hostname which is not the one I was about to use :D so it redirects me to my local 0.74.x beta installation…

**Comment by rgranadino** [comment]
😌
