### ISSUE TITLE
many provisioning errors / packages not installed

### ISSUE THREAD

**Issue by leesbian** [rgranadino/mage2_vagrant#4]
I got a whole load of provisioning notices, and it seems that things have not installed as expected

==> default: Notice: /Stage[main]//Package[libapache2-mod-fastcgi]/ensure: ensure changed 'purged' to 'latest'
==> default: Error: Could not update: Execution of '/usr/bin/apt-get -q -y -o DPkg::Options::=--force-confold install apache2-suexec' returned 100: Reading package lists...
==> default: Building dependency tree...
==> default: Reading state information...
==> default: The following NEW packages will be installed:
==> default:   apache2-suexec
==> default: 0 upgraded, 1 newly installed, 0 to remove and 60 not upgraded.
==> default: Need to get 107 kB of archives.
==> default: After this operation, 184 kB of additional disk space will be used.
==> default: WARNING: The following packages cannot be authenticated!
==> default:   apache2-suexec
==> default: E: There are problems and -y was used without --force-yes
==> default: 
==> default: 
==> default: Error: /Stage[main]//Package[apache2-suexec]/ensure: change from purged to latest failed: Could not update: Execution of '/usr/bin/apt-get -q -y -o DPkg::Options::=--force-confold install apache2-suexec' returned 100: Reading package lists...
==> default: Building dependency tree...
==> default: Reading state information...
==> default: The following NEW packages will be installed:
==> default:   apache2-suexec
==> default: 0 upgraded, 1 newly installed, 0 to remove and 60 not upgraded.
==> default: Need to get 107 kB of archives.
==> default: After this operation, 184 kB of additional disk space will be used.
==> default: WARNING: The following packages cannot be authenticated!
==> default:   apache2-suexec
==> default: E: There are problems and -y was used without --force-yes
==> default: 
==> default: Error: Could not update: Execution of '/usr/bin/apt-get -q -y -o DPkg::Options::=--force-confold install vim' returned 100: Reading package lists...
==> default: Building dependency tree...
==> default: Reading state information...
==> default: The following extra packages will be installed:
==> default:   libgpm2 vim-runtime
==> default: Suggested packages:
==> default:   gpm ctags vim-doc vim-scripts
==> default: The following NEW packages will be installed:
==> default:   libgpm2 vim vim-runtime
==> default: 0 upgraded, 3 newly installed, 0 to remove and 60 not upgraded.
==> default: Need to get 5484 kB of archives.
==> default: After this operation, 24.9 MB of additional disk space will be used.
==> default: WARNING: The following packages cannot be authenticated!
==> default:   libgpm2 vim-runtime vim
==> default: E: There are problems and -y was used without --force-yes
==> default: 
==> default: Error: /Stage[main]//Package[vim]/ensure: change from purged to latest failed: Could not update: Execution of '/usr/bin/apt-get -q -y -o DPkg::Options::=--force-confold install vim' returned 100: Reading package lists...
==> default: Building dependency tree...
==> default: Reading state information...
==> default: The following extra packages will be installed:
==> default:   libgpm2 vim-runtime
==> default: Suggested packages:
==> default:   gpm ctags vim-doc vim-scripts
==> default: The following NEW packages will be installed:
==> default:   libgpm2 vim vim-runtime
==> default: 0 upgraded, 3 newly installed, 0 to remove and 60 not upgraded.
==> default: Need to get 5484 kB of archives.
==> default: After this operation, 24.9 MB of additional disk space will be used.
==> default: WARNING: The following packages cannot be authenticated!
==> default:   libgpm2 vim-runtime vim
==> default: E: There are problems and -y was used without --force-yes
==> default: 
==> default: Notice: /Stage[main]//File[/home/vagrant/bin/reinstall]/ensure: defined content as '{md5}77f9d6ccbd2563fba6d15f0b9725c5f5'

...

==> default: Notice: /Stage[main]//Exec[remove-local-xml]/returns: /bin/rm: cannot remove `/vagrant/data/magento2/app/etc/local.xml': No such file or directory
==> default: Error: /bin/rm /vagrant/data/magento2/app/etc/local.xml returned 1 instead of one of [0]
==> default: Error: /Stage[main]//Exec[remove-local-xml]/returns: change from notrun to 0 failed: /bin/rm /vagrant/data/magento2/app/etc/local.xml returned 1 instead of one of [0]
==> default: Notice: /Stage[main]//Exec[reload-php5-fpm]: Triggered 'refresh' from 6 events

...

The following SSH command responded with a non-zero exit status.
Vagrant assumes that this means the command failed!

puppet apply --manifestdir /tmp/vagrant-puppet-4/manifests --detailed-exitcodes /tmp/vagrant-puppet-4/manifests/mage.pp

and once provisioning has completed :

stdin: is not a tty
Error: Could not update: Execution of '/usr/bin/apt-get -q -y -o DPkg::Options::=--force-confold install apache2-suexec' returned 100: Reading package lists...
Building dependency tree...
Reading state information...
The following NEW packages will be installed:
  apache2-suexec
0 upgraded, 1 newly installed, 0 to remove and 60 not upgraded.
Need to get 107 kB of archives.
After this operation, 184 kB of additional disk space will be used.
WARNING: The following packages cannot be authenticated!
  apache2-suexec
E: There are problems and -y was used without --force-yes

Error: /Stage[main]//Package[apache2-suexec]/ensure: change from purged to latest failed: Could not update: Execution of '/usr/bin/apt-get -q -y -o DPkg::Options::=--force-confold install apache2-suexec' returned 100: Reading package lists...
Building dependency tree...
Reading state information...
The following NEW packages will be installed:
  apache2-suexec
0 upgraded, 1 newly installed, 0 to remove and 60 not upgraded.
Need to get 107 kB of archives.
After this operation, 184 kB of additional disk space will be used.
WARNING: The following packages cannot be authenticated!
  apache2-suexec
E: There are problems and -y was used without --force-yes

Error: Could not update: Execution of '/usr/bin/apt-get -q -y -o DPkg::Options::=--force-confold install vim' returned 100: Reading package lists...
Building dependency tree...
Reading state information...
The following extra packages will be installed:
  libgpm2 vim-runtime
Suggested packages:
  gpm ctags vim-doc vim-scripts
The following NEW packages will be installed:
  libgpm2 vim vim-runtime
0 upgraded, 3 newly installed, 0 to remove and 60 not upgraded.
Need to get 5484 kB of archives.
After this operation, 24.9 MB of additional disk space will be used.
WARNING: The following packages cannot be authenticated!
  libgpm2 vim-runtime vim
E: There are problems and -y was used without --force-yes

Error: /Stage[main]//Package[vim]/ensure: change from purged to latest failed: Could not update: Execution of '/usr/bin/apt-get -q -y -o DPkg::Options::=--force-confold install vim' returned 100: Reading package lists...
Building dependency tree...
Reading state information...
The following extra packages will be installed:
  libgpm2 vim-runtime
Suggested packages:
  gpm ctags vim-doc vim-scripts
The following NEW packages will be installed:
  libgpm2 vim vim-runtime
0 upgraded, 3 newly installed, 0 to remove and 60 not upgraded.
Need to get 5484 kB of archives.
After this operation, 24.9 MB of additional disk space will be used.
WARNING: The following packages cannot be authenticated!
  libgpm2 vim-runtime vim
E: There are problems and -y was used without --force-yes

Error: /bin/rm /vagrant/data/magento2/app/etc/local.xml returned 1 instead of one of [0]
Error: /Stage[main]//Exec[remove-local-xml]/returns: change from notrun to 0 failed: /bin/rm /vagrant/data/magento2/app/etc/local.xml returned 1 instead of one of [0]

**Comment by rgranadino** [comment]
Closing this issue since its a bit old and both magento 2 + this VM have changed a bit since it was initially opened. Please reopen if you're still having issues.
