### ISSUE TITLE
"Installation is incomplete." during Step 6: Install

### ISSUE THREAD

**Issue by csmarvz** [rgranadino/mage2_vagrant#40]
Hello!

Operations go smoothly until the final step of the setup, failing at 65%
Console Log doesn't speak so much, last line being "Installing user configuration..."

![image](https://cloud.githubusercontent.com/assets/2411778/10694729/1ac4a386-79a0-11e5-9083-29f3cf9b792d.png)

Have you any idea what it could be? My host environment is Windows 8.1

I also have a strange issue while trying to use "reinstall" command
![image](https://cloud.githubusercontent.com/assets/2411778/10694810/8ea75b18-79a0-11e5-85a4-49b8db09f242.png)

Have good day,

Henry

**Comment by therouv** [comment]
Hi @csmarvz The recommended installation process is via CLI for now since the web installer seems to be quite buggy right now. 

As for the missing command: Please try to run `vagrant provision` on your host system again so that the vagrant box will contain all the files.
