### ISSUE TITLE
error during install (Step 6) and successful fix

### ISSUE THREAD

**Issue by samfullman** [rgranadino/mage2_vagrant#41]
Thanks for your very clear readme file @rgranadino !  This is my first vagrant install outside of work.
So here's the deal:
Everything worked just fine until I did the Magento install process, and according to the console.log below the progress bar ( at mage2.dev/install ), We failed during catalog products installation.  There was an error but I don't recall the exact wording.  At this point I didn't think to try pressing the "Try Again" button at the top.

Oh, and also the "install sample data" checkbox was grayed out (I remember getting a sick feeling that something was going to go wrong...)

Then I found this video:
https://www.youtube.com/watch?v=d_31MyPT1YI - and go to 11:21 on the time

You'll see he's adding "magento/sample-data" and "magento/sample-data-media" in the `require` portion of composer.json.  So I did that in your composer.json file as well.

Ran the entire process from scratch just to be sure, and this time:
1. I still got a halt in the progress bar at Installing catalog data at about 67%, but with no error message
2. I then had the bright idea to try the "Try again" button.  This got me to like 96% and it stopped with "Installing catalog search" and stopped again
3. One more click of the "Try Again" button and it was successfully installed.

Perhaps adding these two sample-data required lines will be helpful, but the Readme should also mention the "Try Again" button.  Typical Magento ;) ..

**Comment by rgranadino** [comment]
Hi @samfullman ,

Thanks for the detailed bug report it helps a lot and might give some insight as to why others might have run into issues (see #40). I have noticed the web installer to be quite buggy (see #37) with things not always being reproducible or breaking at random steps. 

The `composer.json` file is provided within the magento2 submodule, it's not a file managed in this repository. It would be possible to change it during the provisioning but perhaps a better approach is to update the README.md. I had noticed that the sample data wasn't available in the web install and it makes sense now. In the `reinstall.sh` script if the flag for sample data is pass then `composer require magento/sample-data:1.0.0-beta --dev` is ran which ends up modifying the `composer.json` file.  

If the installation steps were split up into two options: 
 1. CLI installation
 2. Web installation containing instructions to modify the `composer.json` file (or run the composer command)  and try clicking the "Try Again" button if things fail along the way.

Do you think that would be a workable solution for this? I'm hesitant to modify the composer.json file on provision.

**Comment by samfullman** [comment]
Hi Beeplogic, I'll take a look at this but am just learning.  I was able 
to get M2 installed, but the sample data package did NOT come through.  
I'm still trying to get the sample data imported in on top.

I know for that, that if you pull the `develop` branch of M2 and install 
it, you need to pull the corresponding sample-data branch. But still no 
success.

Thanks for replying, and again, I'll take a look at this.  So many new 
concepts!

Sam

**Comment by therouv** [comment]
Hi @samfullman Can you please try with the latest code from this vagrant box? It provides the latest M2 release (2.0.0-rc) and the latest sample data for Magento2. 

If you run "reinstall -s" within the vagrant box, the sample data will be automatically linked and installed during the Magento installation via CLI.

If you want to use the web installer, you need to link the sample data manually before you start the web installation process. See https://github.com/rgranadino/mage2_vagrant/blob/master/files/reinstall.sh#L35 for reference.
