### ISSUE TITLE
Puppet fails on install (vagrant up)

### ISSUE THREAD

**Issue by DrOctogon** [rgranadino/mage2_vagrant#43]
```ssh-agent``` is running on my host machine, github is using the correct key. Still the intial ```vagrant up``` fails with the error below. Am I missing something?

```
==> default: Error: Puppet::Parser::AST::Resource failed with error ArgumentError: Could not find declared class composer at /tmp/vagrant-puppet/manifests-a11d1078b1b1f2e3bdea27312f6ba513/mage.pp:33 on node mage2.dev
==> default: Error: Puppet::Parser::AST::Resource failed with error ArgumentError: Could not find declared class composer at /tmp/vagrant-puppet/manifests-a11d1078b1b1f2e3bdea27312f6ba513/mage.pp:33 on node mage2.dev
The SSH command responded with a non-zero exit status. Vagrant
assumes that this means the command failed. The output for this command
should be in the log above. Please read the output to determine what
went wrong.
```

**Comment by therouv** [comment]
HI @DrOctogon it seems that you cloned the repository but the submodules are not initialized yet. 

Could you please try running `git submodule update --init --recursive`? Or remove the repository on your host machine and clone the repository again recursively (recommended): ``git clone --recursive https://github.com/rgranadino/mage2_vagrant.git`.

**Comment by DrOctogon** [comment]
@therouv my apologies I did indeed miss something. Everything worked once the submodules were installed.

**Comment by therouv** [comment]
@DrOctogon Great!
