### ISSUE TITLE
404 for magento-composer-1.0.2.0.zip

### ISSUE THREAD

**Issue by TheBlogHouse** [rgranadino/mage2_vagrant#46]
Great work but when trying to get this running the first time I'm getting a 404 for the following file when trying to run composer install:

https://repo.magento.com/archives/magento/composer/magento-composer-1.0.2.0.zip

**Comment by therouv** [comment]
Hi @TheBlogHouse you need to add your Magento Connect login credentials to your composer auth.json (~/.composer/auth.json), e.g. like this:

```json
{
    "http-basic": {
        "repo.magento.com": {
            "username": "MAGENTO_USER",
            "password": "MAGENTO_PASS"
        }
    }
}
```

**Comment by TheBlogHouse** [comment]
Thanks
