### ISSUE TITLE
host does not work

### ISSUE THREAD

**Issue by kostya7777** [rgranadino/mage2_vagrant#47]
After install and vagrant up
Can not open hosts "192.168.56.10 mage2.dev" on browser.
/etc/hosts file was effected
Ssh working fine. 

In install I get error
==> default: Error: Puppet::Parser::AST::Resource failed with error ArgumentError: Could not find declared class composer at /tmp/vagrant-puppet/manifests-a11d1078b1b1f2e3bdea27312f6ba513/mage.pp:33 on node mage2.dev
==> default: Error: Puppet::Parser::AST::Resource failed with error ArgumentError: Could not find declared class composer at /tmp/vagrant-puppet/manifests-a11d1078b1b1f2e3bdea27312f6ba513/mage.pp:33 on node mage2.dev
The SSH command responded with a non-zero exit status. Vagrant
assumes that this means the command failed. The output for this command
should be in the log above. Please read the output to determine what
went wrong.

I do not know if it depend to problem.
Please advise I try in win7 and ios system

**Comment by therouv** [comment]
Hi @kostya7777 it seems that you cloned the repository but the submodules are not initialized yet.

Could you please try running `git submodule update --init --recursive`? Or remove the repository on your host machine and clone the repository again recursively (recommended): `git clone --recursive https://github.com/rgranadino/mage2_vagrant.git`.

**Comment by rgranadino** [comment]
@therouv this seems to be a common problem, we should try to add that recursive git command in the README to hopefully catch a few of these?

**Comment by therouv** [comment]
@rgranadino Fixed: https://github.com/rgranadino/mage2_vagrant#installation
