### ISSUE TITLE
Extremely slow

### ISSUE THREAD

**Issue by encodes** [rgranadino/mage2_vagrant#48]
Loading the frontend is taking (with demo data) over 10 seconds. Also seems to not load/render page using correct css. no 404's that i can find.

Admin is responding quickly....  Not sure what has caused this.

**Comment by therouv** [comment]
HI @encodes Is the page faster if you reload the generated page? if yes, then the slow frontend can be explained with Magento internal behaviour: code generation on the fly, less preprocessor, etc..

**Comment by encodes** [comment]
I've cleared all cahces and it's down to entire page load in 3.5 seems much quicker.

For reference loading magento 1 - clean install was under 1 second to load pages.... Seems useable now... Thanks

**Comment by therouv** [comment]
You can always open an issue in https://github.com/magento/magento2 if you encounter any problems/issues with Magento2 and you think this is a bug.

**Comment by encodes** [comment]
Yeah, I've got magento 2 installed locallaly (not using vagrant) and its performance was much better, but i will see if there is anything I notice and let you knw

**Comment by encodes** [comment]
I've ran magento 2 locally, and its 1000x faster. I know there will be some overhead running a VM but its extreme. I'm not sure if its the set-up or what but its unusable... anyone had a better experenice with it

**Comment by rgranadino** [comment]
What is the OS of the host machine? Virtual box (vboxfs) does have some issues when dealing with a lot of i/o. I don't doubt the performance is bad but it should be "bearable". Also note that this VM isn't meant to be of 'production' quality for use within a development of a real site. It's primary goal is to provide a quick way to install and research magento 2. 

We're open to suggestions and things to look at to improve performance from community members which have more experience in that area.

**Comment by comunidademagento** [comment]
Hello @rgranadino 

The host Machine is Ubuntu 15.10

I try use to development.

See image.

The process is stopped here ...

[Progress: 247 / 362]
Module 'Magento_Customer':
Installing data.. 

![captura de tela de 2015-11-24 16-09-25](https://cloud.githubusercontent.com/assets/7476455/11376054/c4de5f22-92c5-11e5-97e5-63cb4e10b5c7.png)
