### ISSUE TITLE
vagrant up needs password

### ISSUE THREAD

**Issue by MaxHill** [rgranadino/mage2_vagrant#54]
i'm trying to run vagrant up but it keeps asking me for admin password at:

Exporting NFS shared folders...
==> default: Preparing to edit /etc/exports. Administrator privileges will be required...
Password:

None of the passwords in the readme works here...

**Comment by rgranadino** [comment]
Hi @MaxHill, the password being requested is the one of your current shell user. Presumably vagrant is running a sudo command to modify the /etc/exports file to setup the shared NFS folders.

**Comment by MaxHill** [comment]
Yeah, i though so too but it does not work with "vagrant" either..

**Comment by MaxHill** [comment]
It turned out to be my password on the host machine it was asking for! Silly me, thanks for the fast reply!
