### ISSUE TITLE
Can not work on my windows 8.1 Oracle VirtualBox.

### ISSUE THREAD

**Issue by tshuy** [rgranadino/mage2_vagrant#6]
I follow the read.me file, but when I use the url 'http://mage2.dev' on my browser.  I got the error message: The webpage is not available.  I got the same error when I type the following urls on my browser:  http://mage2.dev:88/server-status, http://mage2.dev:88/fpm-status.

Please elaborate the install environment.  I got nothing output to the prompt window when I type 'git submodule update --init' from my git bash.

**Comment by therouv** [comment]
@tshuy Can we close this issue?
